# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033
# Do not warn for "Inline HTML"
MD033: false

# https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md036
# Do not warn for "Emphasis used instead of a heading"
MD036: false

# https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md013
# Do not warn for "Line length"
MD013:
  # We can lower this and wrap lines. Markdown does not care.
  line_length: 999

# https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md034
# Do not warn for "Bare URL used"
MD034: false

# https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md026
# Do not warn for "Trailing punctuation in heading"
MD026: false

# https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md014
# Do not warn for "Dollar signs used before commands without showing output"
MD014: false

# Multiple headings with the same content
# Do not warn for "Multiple headings with the same content"
MD024: false
