name: Test deployment

on:
  pull_request:
    branches:
      - main
      - Project-Broom
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env: 
          NODE_OPTIONS: "--max-old-space-size=7168"
        
      - name: Test build website
        run: yarn build
        env: 
          NODE_OPTIONS: "--max-old-space-size=7168"
